export default {
  ROLES: {
    HEALTH_ACTOR: "Acteur de la santé",
    RESEARCHER: "Chercheur",
    INDUSTRIAL: "Industriel",
    ARRAY: ["Acteur de la santé", "Chercheur", "Industriel"]
  },

  HEALTH_NETWORKS: [
    "AllisNa",
    "Pole Pharma"
  ],

  CARE_SERVICES: [
    "Chirurgie",
    "Médecine",
    "Urgence",
    "Bloc opératoire"
  ],

  SUPPORT_SERVICES: [
    "Pharmacie",
    "Analyse",
    "Hygiéniste"
  ],

  RESEARCH_DEPARTMENTS: [
    "Sciences biologiques et médicales",
    "Santé publique",
    "Sciences et technologies pour la santé",
    "Sciences de l’environnement",
    "Sciences de l’ingénierie et du numérique",
    "Sciences de la matière et du rayonnement",
    "Sciences archéologiques"
  ],

  RESEARCH_UNITS: [
    "Archéosciences-Bordeaux : Matériaux, temps, Images et Sociétés",
    "Acides nucléiques : régulations naturelles et artificielles",
    "Biologie du fruit et pathologie",
    "Bordeaux Imaging Center",
    "Biodiversité, gènes et communautés",
    "Bio-imagerie de Bordeaux",
    "Bioingénierie tissulaire et cellulaire",
    "Biologie des maladies cardiovasculaires",
    "Centre de recherche Bordeaux Population Health",
    "Bordeaux Institut of Oncology",
    "Bordeaux Sciences Economiques",
    "Chimie et biologie des membranes et des nano-objets",
    "Centre Émile-Durkheim - Science politique et sociologie comparatives",
    "Cultures et diffusion des savoirs",
    "Centre lasers intenses et applications",
    "Centre d’études et de recherches comparatives sur les constitutions, les Libertés et l’État",
    "Centre européen de recherches en droit des familles, des assurances, des personnes et de la santé",
    "Centre de droit comparé du travail et de la Sécurité sociale",
    "Centre de recherche cardio-thoracique de Bordeaux",
    "Centre de recherche et documentation européennes et internationales",
    "Centre de résonance magnétique des systèmes biologiques",
    "Centre de recherche Paul Pascal",
    "Écophysiologie et génomique fonctionnelle de la vigne",
    "École des neurosciences",
    "Environnements et paléoenvironnements océaniques et continentaux",
    "ESTIA-Recherche",
    "Observatoire de la faune sauvage de Nouvelle Aquitaine",
    "Institut de mécanique et d'ingénierie de Bordeaux",
    "Institut de biochimie et génétique cellulaires",
    "Institut de chimie de la matière condensée de Bordeaux",
    "Institut européen de chimie et biologie",
    "Institut interdisciplinaire de neurosciences",
    "Institut Léon Duguit",
    "Institut de mathématiques de Bordeaux",
    "Immunologie conceptuelle, expérimentale et translationnelle",
    "Institut des maladies neurodégénératives",
    "Laboratoire de l'Intégration du matériau au système",
    "Institut de neurosciences cognitives et intégratives d’Aquitaine",
    "Institut de recherche en droit des affaires et du Patrimoine",
    "Institut de recherche en gestion des organisations",
    "Institut de recherche Montesquieu",
    "Institut de sciences criminelles et de la justice",
    "Institut des sciences moléculaires",
    "Laboratoire d'astrophysique de Bordeaux",
    "Laboratoire d’épistémologie et de didactiques des disciplines",
    "Laboratoire de psychologie",
    "Laboratoire bordelais de recherche en informatique",
    "Laboratoire cultures, éducation, sociétés",
    "Les Afriques dans le monde",
    "Laboratoire de biogenèse membranaire",
    "Laboratoire de chimie des polymères organiques",
    "Laboratoire des composites thermostructuraux",
    "Laboratoire du Futur",
    "Laboratoire ondes et matière d'Aquitaine",
    "Laboratoire de physique des 2 infinis de Bordeaux",
    "Laboratoire photonique, numérique et nanosciences",
    "Neurocentre Magendie",
    "Mésocentre du calcul intensif en Aquitaine",
    "Microbiologie fondamentale et pathogénicité",
    "Maladies rares : génétique et métabolisme",
    "Maison des Sciences de l'Homme de Bordeaux. Territoires plurilingues, Sociétés inclusives, Humanités évolutives",
    "Nutrition et neurobiologie intégrée",
    "Observatoire Aquitain des sciences de l'univers",
    "Unité de recherche en Œnologie",
    "De la Préhistoire à l'actuel : culture, environnement et anthropologie",
    "Pluridisciplinarité au service de l'observation et de la recherche en environnement et astronomie",
    "Sommeil, addiction et neuropsychiatrie",
    "Sciences, philosophie, humanités"
  ],

  CARE_SECTORS: [
    "Dispositifs médicaux",
    "Pharmacie",
    "Logistique"
  ],

  RESEARCH_AREAS: [
    "Pharmacie",
    "Analyse",
    "Hygiéniste",
    "Physique des particules",
    "Astrophysique",
    "Mécanique quantique",
    "Optique",
    "Mécanique des fluides",
    "Géophysique",
    "Physique de la matière condensée",
    "Physique nucléaire",
    "Physique théorique",
    "Physique appliquée",
    "Physique des plasmas",
    "Acoustique",
    "Biochimie",
    "Biologie cellulaire",
    "Génétique",
    "Microbiologie",
    "Neurobiologie",
    "Biologie du développement",
    "Biologie marine",
    "Écologie",
    "Biotechnologie",
    "Immunologie",
    "Virologie",
    "Zoologie",
    "Botanique",
    "Biologie moléculaire",
    "Informatique théorique",
    "Intelligence artificielle",
    "Systèmes d'information",
    "Vision par ordinateur",
    "Cryptographie",
    "Algorithmique",
    "Génie logiciel",
    "Réseaux de neurones",
    "Architecture des ordinateurs",
    "Base de données",
    "Science des matériaux",
    "Ingénierie mécanique",
    "Ingénierie civile",
    "Ingénierie électrique",
    "Ingénierie chimique",
    "Ingénierie aérospatiale",
    "Ingénierie nucléaire",
    "Ingénierie biomédicale",
    "Ingénierie environnementale",
    "Psychologie cognitive",
    "Psychologie clinique",
    "Psychologie du développement",
    "Psychologie sociale",
    "Neuropsychologie",
    "Psychologie de l'éducation",
    "Psychologie du travail",
    "Psychologie du sport",
    "Linguistique",
    "Philosophie",
    "Anthropologie",
    "Sociologie",
    "Histoire",
    "Littérature",
    "Art",
    "Musique",
    "Danse",
    "Théâtre",
    "Film",
    "Photographie",
    "Design",
    "Archéologie",
    "Droit",
    "Économie",
    "Géographie",
    "Science politique",
    "Études de communication",
    "Éducation",
    "Éthique",
    "Études de genre",
    "Études culturelles",
    "Études de développement",
    "Science environnementale",
    "Science de la santé",
    "Nutrition",
    "Kinésiologie",
    "Médecine",
    "Chirurgie",
    "Dentisterie",
    "Optométrie",
    "Physiothérapie",
    "Psychiatrie",
    "Vétérinaire",
    "Enseignement",
    "Administration des affaires",
    "Marketing",
    "Finance",
    "Comptabilité",
    "Ressources humaines",
    "Gestion de la technologie",
    "Management"
  ],

  HEALTH_JOB_TITLE: [
    "Médecin généraliste",
    "Infirmier/infirmière",
    "Chirurgien",
    "Cardiologue",
    "Pédiatre",
    "Gynécologue",
    "Radiologue",
    "Anesthésiste",
    "Dermatologue",
    "Psychologue clinicien",
    "Orthopédiste",
    "Ophtalmologiste",
    "Urgentiste",
    "Pharmacien",
    "Sage-femme",
    "Neurologue",
    "Psychologue du travail",
    "Chirurgien-dentiste",
    "Diététicien(ne)",
    "Kinésithérapeute",
    "Orthophoniste",
    "Gériatre",
    "Médecin du sport",
    "Ostéopathe",
    "Médecin légiste",
    "Pédiatre néonatalogiste",
    "Oncologue",
    "Rhumatologue",
    "Immunologiste",
    "Chiropracteur",
    "Néphrologue",
    "Pédiatre gastro-entérologue",
    "Médecin du travail",
    "Endocrinologue",
    "Pédiatre allergologue",
    "Pédiatre pneumologue",
    "Psychomotricien(ne)",
    "Optométriste",
    "Ergothérapeute",
    "Podologue",
    "Orthoptiste",
    "Orthodontiste",
    "Médecin anesthésiste-réanimateur",
    "Médecin radiologue",
    "Médecin du sommeil",
    "Médecin psychiatre",
    "Médecin addictologue",
    "Médecin de santé publique",
    "Médecin de rééducation fonctionnelle",
    "Médecin urgentiste",
    "Médecin légiste",
    "Médecin anatomopathologiste",
    "Médecin biologiste",
    "Médecin oncologue",
    "Médecin pneumologue",
    "Médecin allergologue",
    "Médecin neurologue",
    "Médecin cardiologue",
    "Médecin ophtalmologiste",
    "Médecin gastro-entérologue",
    "Médecin rhumatologue",
    "Médecin endocrinologue"
  ],

  HEALTH_KEY_WORDS: [
    "Médecine générale",
    "Cardiologie",
    "Chirurgie",
    "Pédiatrie",
    "Gynécologie",
    "Dermatologie",
    "Neurologie",
    "Psychiatrie",
    "Orthopédie",
    "Radiologie",
    "Oncologie",
    "Infectiologie",
    "Anesthésie",
    "Urgences",
    "Ophtalmologie",
    "Oto-rhino-laryngologie",
    "Néphrologie",
    "Pneumologie",
    "Endocrinologie",
    "Gastro-entérologie",
    "Rhumatologie",
    "Médecine du travail",
    "Médecine palliative",
    "Médecine légale",
    "Médecine nucléaire",
    "Kinésithérapie",
    "Orthophonie",
    "Ergothérapie",
    "Psychologie",
    "Diététique",
    "Soins infirmiers",
    "Pharmacologie",
    "Santé publique",
    "Prévention",
    "Hygiène hospitalière",
    "Biochimie",
    "Microbiologie",
    "Immunologie",
    "Pharmacologie clinique",
    "Radiologie médicale",
  ],
}